{% extends "layout.phtml" %}
{% block body %}
	{% include "header.phtml" %}
	<div id="game-section"></div>

	<script type="template" id="game-ongoing">
		Game ongoing
	</script>

	<script type="template" id="game-open">
		Game open
	</script>

	<script type="template" id="game-finished">
		Game finished
	</script>
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/game.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/game.page.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/header.js') }}"></script>
{% endblock %}
