{% extends "layout.phtml" %}
{% block body %}
	{% include "header.phtml" %}

	<div class="container">
		<div id="game-section" class="row">

		</div>
	</div>

	<script type="template" id="game-ongoing">
		<div class="col-sm-9">
			<ul id="board">
				[[each board as cell on board_cell]]
			</ul>
			<div id="player-hand">
				[[each player_hand as token on player_token]]
			</div>
			<div id="play-result"></div>
			<button id="confirm-play" class="btn btn-primary btn-full-width" disabled>Confirm</button>
		</div>
		<div id="player-scores" class="col-sm-3">
			Scores:
			[[each game.game_players as player on player_score]]
		</div>
	</script>

	<script type="template" id="board-token">
		<div class="token" data-value="[[token.value]]">
			[[token.value]]
		</div>
	</script>

	<script type="template" id="player-token">
		<div class="token" id="player-token-[[token.index]]" data-value="[[token.value]]" draggable="true">
			[[token.value]]
		</div>
	</script>

	<script type="template" id="board-cell">
		<li class="cell cell-[[cell.type]]" data-x="[[cell.x]]" data-y="[[cell.y]]">
			[[if cell.token then board_token with cell]]
		</li>
	</script>

	<script type="template" id="game-open">
		Game open
	</script>

	<script type="template" id="game-finished">
		Game finished
	</script>

	<script type="template" id="template-player-score">
		<div class="score">
			<span id="player-[[player.id_user]]">[[player.id_user]]</span>: [[player.score]]
			[[if player.is_game_creator then game_creator]]
			[[if player.is_turn then player_turn]]
		</div>
	</script>

	{% include "game-player-info.phtml" %}
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/game.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/game.page.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/header.js') }}"></script>
{% endblock %}
