{% extends "layout.phtml" %}
{% block body %}
	{% include "header.phtml" %}
	<div id="game-section"></div>

	<script type="template" id="game-ongoing">
		Game ongoing
		<ul id="board">
			[[each board as cell on board_cell]]
		</ul>
		<ul id="player-hand">
			[[each player_hand as token on player_token]]
		</ul>
	</script>

	<script type="template" id="player-token">
		<li>
			<div class="token" id="player-token-[[token.index]]"data-value="[[token.value]]" draggable="true">
				[[token.value]]
			</div>
		</li>
	</script>

	<script type="template" id="board-cell">
		<li class="cell-[[cell.type]]" data-x="[[cell.x]]" data-y="[[cell.y]]">
			[[cell.type]]
		</li>
	</script>

	<script type="template" id="game-open">
		Game open
	</script>

	<script type="template" id="game-finished">
		Game finished
	</script>
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/game.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/game.page.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/header.js') }}"></script>
{% endblock %}
