{% extends "layout.phtml" %}
{% block body %}
	{% include "header.phtml" %}
	<div class="container">
		<div class="row justify-content-md-center">
			<div class="col-sm-6">
				<h3>Games</h3>
				<a class="btn btn-primary btn-full-width" href="/game/create"> Start new game </a>
				<div id="list-games"></div>
			</div>
		</div>
	</div>

	<!-- Templates used by the javascript application to populate the page with data-->
	<!-- Template to represent a game of the current player -->
	<script type="template" id="game-instance">
		<div class="individual-game card">
			<h3>
				[[if game.ongoing then game_link with game]]
				[[if game.open then game_invite_link with game]]
				[[if game.date_finished then game_finished]]
			</h3>
			<h4>Players: [[game.count_players]] / [[game.number_players]]</h5>
			<ul>
				[[each game.players as player on game_player]]
			</ul>
		</div>
	</script>

	<!-- Template to represent a user of a game -->
	<script type="template" id="game-player">
		<li>
			[[player.name]]
			 [[if player.is_game_creator then game_creator]]
			[[if player.is_turn then player_turn]]
		</li>
	</script>

	<!-- Template for the link to a game -->
	<script type="template" id="game-link">
		<a href="/game/[[id_game]]">Go to game</a>
	</script>

	<!-- Template for the link to a game -->
	<script type="template" id="game-finished">
		The game is finished.
	</script>

	<!-- Template for the link to invite a player to a game -->
	<script type="template" id="game-invite-link">
		<span>Invite link: <a href="/game/join/[[public_id]]">Copy link</a>
	</script>
	{% include "game-player-info.phtml" %}
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/game.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/home.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/header.js') }}"></script>
{% endblock %}
