{% extends "layout.phtml" %}
{% block body %}
	{% include "header.phtml" %}
	<h1>My Games</h1>
	<a href="/game/create">Start new game</a>
	<ul id="list-games"></ul>

	<!-- Templates used by the javascript application to populate the page with data-->
	<!-- Template to represent a game of the current player -->
	<script type="template" id="game-instance">
		<li>
			<p>game [[game.public_id]]</p>
			<p>number of players: [[game.current_players_count]] / [[game.number_players]]</p>
			<ul>
				[[each game.game_players as player on game_player]]
			</ul>
		</li>
	</script>

	<!-- Template to represent a user of a game -->
	<script type="template" id="game-player">
		<li>
			Player: [[player]]
		</li>
	</script>
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/home.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/header.js') }}"></script>
{% endblock %}
