<!doctype html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Three 2 Fifteen</title>
		{% if game_id %}
		<meta id="current_game_id" data-value="{{ game_id }}" />
		{% endif %}
		<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/main.css') }}">
	</head>
	<body>
		{% block body %}{% endblock %}
		<script type="text/javascript" src="https://ghislain-rodrigues.fr/js/butterfly.min.js"></script>
		<script type="text/javascript" src="/config.js"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/utils.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/request.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/auth.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/app.js') }}"></script>
		{% block scripts %}{% endblock %}
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/main.js') }}"></script>
	</body>
</html>
